# Generated by Django 2.1.4 on 2018-12-22 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('rating_sum', models.IntegerField()),
                ('rating_cnt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.IntegerField()),
                ('address', models.CharField(max_length=256)),
                ('gender', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='arohi.User')),
            ],
            bases=('arohi.user',),
        ),
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='arohi.User')),
                ('category', models.CharField(max_length=64)),
                ('required_money', models.IntegerField()),
            ],
            bases=('arohi.user',),
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='arohi.User')),
                ('region', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=64)),
                ('investment_range_low', models.IntegerField()),
                ('investment_range_hi', models.IntegerField()),
            ],
            bases=('arohi.user',),
        ),
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arohi.Investor'),
        ),
    ]
